### ISSUE TITLE
ZLS Support

### ISSUE THREAD

**Issue by KeithBrown39423** [BrookJeynes/zigver#1]
Considering the popularity of ZLS, I would recommend adding support to install ZLS through this as well.

**Comment by BrookJeynes** [comment]
That's a good idea. I definitely plan to work on this soon :)

**Comment by BrookJeynes** [comment]
Closing as ZLS can now be installed alongside Zig - https://github.com/BrookJeynes/zigver/commit/e21b974b26b935025767bfc7e9cd68af1440081b
